towards adding Pereira2018ROI as a benchmark
brain-score/language pull request #37
Opened 2022-08-16 23:18 UTC by aalok-sathe

the data file is local for now; not available on s3. We'll share the csv in slack.
this contains means of ROIs for Lang for all subjects, averaged across sessions.

2022-09-20 20:49 UTC, mschrimpf requested changes
High-level comment: I think the benchmark should go inside `pereira2018` rather than a new plugin `pereira2018_v2022` -- @kvfairchild do you agree?

Note that unit tests are failing; if you'd like to put this data onto the S3 bucket that we used for the other data, slack me and I'll get you write access.

2022-09-20 20:49 UTC, mschrimpf commented on .gitignore
> +# brainscore_language/data
dead specification, either delete or leave, no commented code

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/__init__.py
> +}"""
@kvfairchild we're beginning to duplicate this `BIBTEX` quite a lot, e.g. in [`data/pereira2018`](https://github.com/brain-score/language/blob/b03ea2c9ceef646c53a7caedcab9ac13df07354a/brainscore_language/data/pereira2018/__init__.py#L8-L18) and [`benchmarks/pereira2018`](https://github.com/brain-score/language/blob/b03ea2c9ceef646c53a7caedcab9ac13df07354a/brainscore_language/benchmarks/pereira2018/__init__.py#L13-L23). One simple solution might be to replace the `benchmarks` definitions with `from brainscore_language.data.pereira2018 import BIBTEX`, is that acceptable from a plugin perspective? I guess we might run into import errors if dependencies are not installed and potentially encourage direct imports when we want plugins to go through the plugin manager.

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/__init__.py
> +import logging
Shouldn't this just replace the current `pereira2018`? I would say we don't want a new file, but rather want to make this the new version.
Tagging @kvfairchild so she can chime in from the plugins perspective.

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/__init__.py
> +        # ceiling_s3_kwargs: dict = None,
dead code; put on S3

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/__init__.py
> +        # ceiling = self._load_ceiling(identifier=identifier, **ceiling_s3_kwargs)
dead code

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/__init__.py
> +            ceiling_func=None,  # ceiling,
dead code

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/__init__.py
> +        # data = data.sel(experiment=experiment)  # filter experiment
dead code

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/__init__.py
> +    #     return ceiling
lots of dead code

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/__init__.py
> +        score = raw_score  # ceiling_normalize(raw_score, self.ceiling)
dead code

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/ceiling_packaging.py
> +import logging
this entire file seems to be a copy of `pereira2018/ceiling_packaging.py`, I'm not sure what it's doing

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/test.py
> +        # )
dead code

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/test.py
> +    #     }
dead code

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/benchmarks/pereira2018_v2022/test.py
> +    test.test_exact(243)
no need for this, instead run with pytest

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/data/pereira2018_v2022/__init__.py
> +# from brainscore_language.utils.s3 import load_from_s3
dead code

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/data/pereira2018_v2022/__init__.py
> +import logging
Let's talk about whether this goes into its own file or is part of the existing pereira2018 data plugin (I put a note on the agenda)

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/data/pereira2018_v2022/data_packaging.py
> +    # inv_presentation_map = {v: k for k, v in presentation_id_map}
feeling less strongly about it here, but still: dead code :)

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/data/pereira2018_v2022/data_packaging.py
> +    # )
can just reuse https://github.com/brain-score/language/blob/b03ea2c9ceef646c53a7caedcab9ac13df07354a/brainscore_language/utils/s3.py#L12

2022-09-20 20:49 UTC, mschrimpf commented on brainscore_language/data/pereira2018_v2022/test.py
> +        )  # potential TODO: rename to neuroid_id
todo?

2022-10-11 23:16 UTC, mschrimpf commented
@aalok-sathe any updates on this PR?

2022-10-12 19:54 UTC, aalok-sathe commented
should we be concerned by this (warning?) message?
`DEBUG:brainscore_core.metrics:isel on raw values failed: ValueError("Dimensions {'subject'} do not exist. Expected one or more of ('split', 'neuroid')")
`

we encounter it at https://github.com/brain-score/language/blob/b2f24265b4af0470a27fad899ef5391e244dd5ed/brainscore_language/utils/transformations.py#L232 during ceiling computation and aren't sure if this is an issue.
our assembly contains `subject` as a coord but not as a dimension (subject is never a dimension, right? it is along the `neuroid` dimension?)

2022-10-12 20:55 UTC, aalok-sathe commented
We're also looking for some help towards this failure of the test; now that we uploaded to s3 we're not sure why it's failing to find the assembly file in the cache: https://app.travis-ci.com/github/brain-score/language/builds/255739587#L660

2022-10-12 21:42 UTC, mschrimpf commented
> should we be concerned by this (warning?) message? `DEBUG:brainscore_core.metrics:isel on raw values failed: ValueError("Dimensions {'subject'} do not exist. Expected one or more of ('split', 'neuroid')") `

No -- this is just saying that it cannot select on the score's `raw` values, so it is not selecting anything there. Maybe we should turn this into a debug message..

> We're also looking for some help towards this failure of the test; now that we uploaded to s3 we're not sure why it's failing to find the assembly file in the cache: https://app.travis-ci.com/github/brain-score/language/builds/255739587#L660

At least in the build you linked, it's trying to load the file from local disk rather than S3: 
```
brainscore_language/data/pereira2018_v2022/__init__.py:23: in <lambda>
    data_registry["Pereira2018_v2022.language"] = lambda: load_from_disk("Pereira2018ROI")
```

2022-10-13 12:45 UTC, mschrimpf commented on tests/test_test_plugins.py
> +            f.write(textwrap.dedent('''\
fyi this is leading to errors : `TabError: inconsistent use of tabs and spaces in indentation`

2022-10-13 13:20 UTC, aalok-sathe commented
> > We're also looking for some help towards this failure of the test; now that we uploaded to s3 we're not sure why it's failing to find the assembly file in the cache: https://app.travis-ci.com/github/brain-score/language/builds/255739587#L660
> 
> At least in the build you linked, it's trying to load the file from local disk rather than S3:
> 
> ```
> brainscore_language/data/pereira2018_v2022/__init__.py:23: in <lambda>
>     data_registry["Pereira2018_v2022.language"] = lambda: load_from_disk("Pereira2018ROI")
> ```

I think we changed that in the latest commit we pushed yesterday:
https://github.com/brain-score/language/commit/a74399462a68102dd8545c3aa57a6d29e3a946c6

2022-10-13 13:57 UTC, gretatuckute commented on brainscore_language/data/pereira2018_v2022/test.py
> +        )  # potential TODO: rename to neuroid_id
yes to do

2022-10-13 14:08 UTC, mschrimpf commented on brainscore_language/data/pereira2018_v2022/__init__.py
> +)
@aalok-sathe I set the S3 object to public, but I think the issue is that you're attempting to load `assy_Pereira2018ROI` while the S3 file is called `assembly_Pereira2018ROI` -- if you pass `assembly_prefix='assembly'` to https://github.com/brain-score/language/blob/5ea01ce9f619ca23bcce9c54da6c47669def1138/brainscore_language/utils/s3.py#L33, I believe it should work

2022-10-13 14:13 UTC, gretatuckute commented
> > should we be concerned by this (warning?) message? `DEBUG:brainscore_core.metrics:isel on raw values failed: ValueError("Dimensions {'subject'} do not exist. Expected one or more of ('split', 'neuroid')") `
> 
> No -- this is just saying that it cannot select on the score's `raw` values, so it is not selecting anything there. Maybe we should turn this into a debug message..
> 
> > We're also looking for some help towards this failure of the test; now that we uploaded to s3 we're not sure why it's failing to find the assembly file in the cache: https://app.travis-ci.com/github/brain-score/language/builds/255739587#L660
> 
> At least in the build you linked, it's trying to load the file from local disk rather than S3:
> 
> ```
> brainscore_language/data/pereira2018_v2022/__init__.py:23: in <lambda>
>     data_registry["Pereira2018_v2022.language"] = lambda: load_from_disk("Pereira2018ROI")
> ```

It already shows up as a DEBUG message. But I don't think we understand why it would occur there in the first place? In tracks to a brainio script where there is even no "isel" operation?

2022-10-25 20:47 UTC, gretatuckute approved these changes

2022-10-26 03:05 UTC, closed without merging

2022-10-26 03:11 UTC, mschrimpf commented
Sorry, this PR was closed after combining commit history. @aalok-sathe can you please open a new PR?

2022-10-26 23:29 UTC, aalok-sathe commented
No worries! will do!

________________________________
From: Martin Schrimpf ***@***.***>
Sent: Tuesday, 25 October, 2022, 23:11
To: brain-score/language ***@***.***>
Cc: Aalok | आलोक ***@***.***>; Mention ***@***.***>
Subject: Re: [brain-score/language] towards adding Pereira2018ROI as a benchmark (PR #37)


Sorry, this PR was closed after combining commit history. @aalok-sathe<https://github.com/aalok-sathe> can you please open a new PR?